In [1]:
x = [1,2,3,4,5]
y = [i-0.75 for i in x]
print(y)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [3]:
import numpy as np

In [4]:
# array
x = np.arange(0, 10, 2)
print(x)
print(type(x))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [5]:
y = x -0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [6]:
np.average()
np.min()
np.mean()
np.median()

TypeError: average() missing 1 required positional argument: 'a'

In [7]:
a_list = [i for i in range(1, 11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
a_array = np.asarray(a_list)
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [7]:
x = [1,2,3]
y = [1,4,5]
x_np = np.asarray(x)
y_np = np.asarray(y)
c = x_np*y_np
print(c)

[ 1  8 15]


In [8]:
np.min(x)
np.max(y_np)

5

In [22]:
atsitiktinis = np.random.randint(0,10, 100)  # siame sarase bus lygiai 100 elementu tarp ribu 0 ir 10. Ribas butinai turime nurodyti.
print(atsitiktinis)

[2 9 4 6 1 7 4 8 5 3 5 9 5 9 5 4 8 3 2 1 1 3 8 6 3 7 8 2 4 0 2 1 9 9 8 5 3
 6 9 1 3 2 3 0 7 7 6 8 2 5 7 0 8 9 2 0 7 6 0 8 4 4 1 0 5 6 4 2 0 7 8 6 5 5
 2 9 2 2 7 7 7 3 7 8 2 8 0 4 5 9 9 6 8 1 2 1 5 6 1 8]


In [26]:
atsitiktinis_float = np.random.rand(100) # ribos yra tarp 0 ir 1, tik nurodome kiek norime skaiciu 100,200...
print(atsitiktinis_float)

[0.42609964 0.39662345 0.84101005 0.51618857 0.00963625 0.23841803
 0.58796588 0.846694   0.8034774  0.80518356 0.32993987 0.0834094
 0.67038491 0.61593872 0.12229244 0.69338293 0.20890864 0.46312756
 0.93698712 0.29522791 0.89438807 0.49051416 0.64318959 0.98423708
 0.94106711 0.55476045 0.42049647 0.06508006 0.2204511  0.6588655
 0.36738324 0.47249512 0.05489685 0.06577469 0.7591358  0.75062497
 0.81846245 0.28301303 0.38625409 0.23552986 0.62616071 0.31911113
 0.91211931 0.69302081 0.54818109 0.08559222 0.3085235  0.04918946
 0.66516932 0.81002965 0.76719816 0.18269935 0.2665594  0.58614433
 0.67628716 0.99874854 0.05011611 0.14470837 0.26619607 0.18211326
 0.15994204 0.46848857 0.17676047 0.81684042 0.3232431  0.74320501
 0.07385124 0.24252206 0.56380036 0.47725363 0.56576325 0.98394333
 0.4437279  0.22251446 0.39502655 0.67366276 0.79159823 0.81433938
 0.67997743 0.88491922 0.02734005 0.46272019 0.55896213 0.8790271
 0.38039045 0.86906221 0.2785389  0.96402401 0.89730169 0.9642787

In [49]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
#mean(vidurkis, grieztai aritmetinis) ir average(galime nurodyti svertus)
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas, weights=svoriai)
print(sv_vid)
# median()
medx = np.median(xas)
print(medx, np.min(xas), np.max(xas))

4.46
4.310815921721679
4.0 1 9


In [57]:
l = np.linspace(0,10,15) #(.........endpoint=False) jeigu nenorite, kad itrauktu paskutini skaiciu
print(l)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [61]:
# asarray, arange, min, max, mena, average, median
n_np = np.arange(0,10)
# kaip metodai
minn = n_np.min()
print(minn)
print(n_np.mean())
print(n_np.max())

0
4.5
9


In [14]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
%autoreload 2
import modulis

In [8]:
print(modulis.A)

70


In [17]:
modulis.printA()

As esu nauja printA() funkcija
Dar vienas pakeitimas
Paskutinis pakeitimas


In [19]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases
# į modulį
# ir patikrinkite klasių veikimą
# sukurdami kintamuosius ir patikrindami jų veikimą

test = modulis.Car(P='Automobilis', R=5000, S=5)
print(test.GetSeats())

test = modulis.Bus(P='Autobusas', R=10000, S=40)
print(test.GetSeats())

test = modulis.Train(P='Traukinys', R=20000, S=100)
print(test.GetSeats())

Automobilis turi 5 sedimas vietas
Autobusas turi 40 sedimu vietu 
Traukinys turi 100 sedimu vietu


In [7]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

class FailoSkaitytuvas():
    def __init__(self, failo_pavadinimas):
        self.I = []
        self.U = []
        self.j = []
        self.P = []
        self.failo_pavadinimas = failo_pavadinimas

    def skaityti_faila(self):
        with open(self.failo_pavadinimas, 'r') as failas:
            lines = failas.readlines()
            for line in lines:
                values = line.split()
                self.I.append(float(values[0]))
                self.U.append(float(values[1]))
                self.j.append(float(values[2]))
                self.P.append(float(values[3]))

    def pce_dydis(self):
        Pmax = max(self.P)
        pce = Pmax / 1000 * 100
        return pce


# Pavyzdinis failas "duomenys.txt":
# 1.2 3.4 5.6 7.8
# 2.3 4.5 6.7 8.9
# ...

# Sukuriame objektą FailoSkaitytuvas
fs = FailoSkaitytuvas("REF_D_5k_FW_2.03.dat")

# Nuskaitome failą
fs.skaityti_faila()

# Atspausdiname skaičių sąrašus
print("I:", fs.I)
print("U:", fs.U)
print("j:", fs.j)
print("P:", fs.P)

# Gauti ir atspausdinti pce dydį
print("PCE dydis:", fs.pce_dydis())

ValueError: could not convert string to float: 'U[V]'

In [6]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti
class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
    def dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines() # suformuoja teksta kaip eiluciu sarasa
        file.close()
        print(sarasas) # pasitikrinam ar veikia
        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))
        print(self.I)
        print(self.U) 
        print(self.j) 
        print(self.p) 
    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat', ';') #pasitikrinam ar nuskaito info is failo
sarasas.dataReader()
print(sarasas.getPCE())

['U[V] ; I[A] ; j[mA/cm^2] ; P[mW/cm^2]\n', '1.2 ; 0.0010878 ; 13.59755 ; 16.31706\n', '1.1766667 ; 0.0008779 ; 10.9735512 ; 12.912212\n', '1.1533333 ; 0.000675 ; 8.4376562 ; 9.7314302\n', '1.13 ; 0.0004624 ; 5.780055 ; 6.5314621\n', '1.1066667 ; 0.0002595 ; 3.2442637 ; 3.5903185\n', '1.0833333 ; 7.83e-05 ; 0.9787641 ; 1.0603278\n', '1.06 ; -7.92e-05 ; -0.9902056 ; -1.049618\n', '1.0366667 ; -0.0002111 ; -2.63856 ; -2.7353072\n', '1.0133333 ; -0.0003275 ; -4.0936325 ; -4.1482143\n', '0.99 ; -0.0004257 ; -5.3214875 ; -5.2682726\n', '0.9666667 ; -0.0005053 ; -6.3163262 ; -6.105782\n', '0.9433333 ; -0.0005775 ; -7.2184413 ; -6.8093962\n', '0.92 ; -0.0006322 ; -7.9018762 ; -7.2697261\n', '0.8966667 ; -0.0006841 ; -8.55161 ; -7.6679436\n', '0.8733333 ; -0.0007236 ; -9.0446012 ; -7.8989518\n', '0.85 ; -0.0007626 ; -9.5324562 ; -8.1025878\n', '0.8266667 ; -0.0007935 ; -9.9188812 ; -8.1996085\n', '0.8033333 ; -0.00082 ; -10.2496088 ; -8.2338524\n', '0.78 ; -0.000844 ; -10.54984 ; -8.2288752\n'

AttributeError: 'keturiolika_failu' object has no attribute 'p'

In [8]:
#RASOS SPRENDIMAS
class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
        self.p = []
        self.__dataReader() # kreipiasi i dataReader; __ padar privaciu ir naudojami tik klases viduje
    def __dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines()
        file.close()
        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))
    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat',';')
# sarasas.__dataReader()
print(sarasas.getPCE())

1.63


In [9]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [10]:
pip install pandas

  Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 1.3 MB/s eta 0:00:09
   - -------------------------------------- 0.3/11.5 MB 4.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/11.5 MB 9.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/11.5 MB 11.2 MB/s eta 0:00:01
   --------- ------------------------------ 2.7/11.5 MB 13.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.8/11.5 MB 15.1 MB/s eta 0:00:01
   ----------------- ---------------------- 5.1/11.5 MB 17.2 MB/s eta 0:00:01
   ----------------------- ---------------- 6.7/11.5 MB 19.5 MB/s eta 0:00:01
   ------------------------------ --------- 8.6/11.5 MB 22.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.8/11.5 MB 29.7 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 31.2 MB/s eta 0:00:01
  

In [11]:
import pandas as pd

In [12]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [13]:
import matplotlib.pyplot as plt